### ISSUE TITLE
__init__.py issues on CentOS 6.8

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-sdk-python#21]
I built Python 3.5 from source as CentOS 6 doesn't have python3, so maybe that's why.
```
[root@centos1 solidfire-sdk-python-master]# python3.5 -V
Python 3.5.3
[root@centos1 solidfire-sdk-python-master]# python3.5 setup.py test
running test
Searching for requests>=2.9.1
Best match: requests 2.13.0
Processing requests-2.13.0-py3.5.egg

Using /data/solidfire-python-sdk/solidfire-sdk-python-master/.eggs/requests-2.13.0-py3.5.egg
Searching for enum34>=1.1.6
Best match: enum34 1.1.6
Processing enum34-1.1.6-py3.5.egg

Using /data/solidfire-python-sdk/solidfire-sdk-python-master/.eggs/enum34-1.1.6-py3.5.egg
Searching for future>=0.15.2
Best match: future 0.16.0
Processing future-0.16.0-py3.5.egg

Using /data/solidfire-python-sdk/solidfire-sdk-python-master/.eggs/future-0.16.0-py3.5.egg
/usr/local/lib/python3.5/site-packages/setuptools/dist.py:364: UserWarning: Module enum was already imported from /usr/local/lib/python3.5/enum.py, but /data/solidfire-python-sdk/solidfire-sdk-python-master/.eggs/enum34-1.1.6-py3.5.egg is being added to sys.path
  pkg_resources.working_set.add(dist, replace=True)
running egg_info
writing requirements to solidfire_sdk_python.egg-info/requires.txt
writing dependency_links to solidfire_sdk_python.egg-info/dependency_links.txt
writing top-level names to solidfire_sdk_python.egg-info/top_level.txt
writing solidfire_sdk_python.egg-info/PKG-INFO
reading manifest file 'solidfire_sdk_python.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'LICENSE'
warning: no files found matching 'README.rst'
warning: no previously-included files matching '*.pyc' found under directory 'solidfire'
writing manifest file 'solidfire_sdk_python.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 95, in <module>
    'clean': Clean,
  File "/usr/local/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/test.py", line 210, in run
    self.run_tests()
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/test.py", line 231, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/local/lib/python3.5/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/usr/local/lib/python3.5/unittest/main.py", line 123, in parseArgs
    self._do_discovery([])
  File "/usr/local/lib/python3.5/unittest/main.py", line 228, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/local/lib/python3.5/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/local/lib/python3.5/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/usr/local/lib/python3.5/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/usr/local/lib/python3.5/site-packages/setuptools/command/test.py", line 42, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/local/lib/python3.5/unittest/loader.py", line 153, in loadTestsFromName
    module = __import__(module_name)
  File "/data/solidfire-python-sdk/solidfire-sdk-python-master/tests/test_requests.py", line 4, in <module>
    from solidfire.common import ApiServerError
  File "/data/solidfire-python-sdk/solidfire-sdk-python-master/solidfire/__init__.py", line 52
    <<<<<<< 2a7c6b9c0af69f977e824fd1b8655429eca10f92
     ^
SyntaxError: invalid syntax
````
I don't know if tests are supposed to pass in the first place, but I built and installed and then tried with the built-in Python2.6 (not supported, I know) and it throws the same error.
```
Using /usr/lib/python2.6/site-packages/importlib-1.0.4-py2.6.egg
Finished processing dependencies for solidfire-sdk-python==1.2.0.108
[root@centos1 solidfire-sdk-python-master]# python sf-test.py
Traceback (most recent call last):
  File "sf-test.py", line 2, in <module>
    from solidfire.factory import ElementFactory
  File "/usr/lib/python2.6/site-packages/solidfire_sdk_python-1.2.0.108-py2.6.egg/solidfire/__init__.py", line 52
    <<<<<<< 2a7c6b9c0af69f977e824fd1b8655429eca10f92
     ^
SyntaxError: invalid syntax
```

Problematic part:

```
        """

        ServiceBase.__init__(self, mvip, username, password, api_version,
                             verify_ssl, dispatcher)

<<<<<<< 2a7c6b9c0af69f977e824fd1b8655429eca10f92
=======
    def add_account(
            self,
            username,
            initiator_secret=OPTIONAL,
            target_secret=OPTIONAL,
            attributes=OPTIONAL,):
        """

```

Is this method (setup.py install) not supported?

**Comment by ahaid** [comment]
The problem here is the master branch is corrupted with some bad merge conflicts. This will be fixed soon. In the meantime, you can switch to the [1.2 release branch](https://github.com/solidfire/solidfire-sdk-python/tree/release1.2) and try again.

**Comment by scaleoutsean** [comment]
OK. Yep, v1.2 builds and tests fine.
The "build" repo badge: status is green ("passing"). Strange indicator. They should start providing several shades of green ;-)
