### ISSUE TITLE
407 Proxy Authentication Required

### ISSUE THREAD

**Issue by kgrvamsi** [solidfire/solidfire-sdk-python#32]
Hi Need help on how to resolve the following issue.

``(donttouch) root@<someserver>:~# python solid-fire.py   
2017-12-19 15:53:12,152 - solidfire.Element - INFO - {"params": {}, "method": "GetAPI", "id": 0}
Traceback (most recent call last):
  File "solid-fire.py", line 4, in <module>
    sfe = ElementFactory.create("<storage array ip>", "username", "password")
  File "/root/donttouch/local/lib/python2.7/site-packages/solidfire/factory.py", line 87, in create
    api = element.get_api()
  File "/root/donttouch/local/lib/python2.7/site-packages/solidfire/__init__.py", line 668, in get_api
    since=1.0
  File "/root/donttouch/local/lib/python2.7/site-packages/solidfire/common/__init__.py", line 620, in send_request
    raise ApiConnectionError(e)
solidfire.common.ApiConnectionError: HTTPSConnectionPool(host='<storage array ip>', port=443): Max retries exceeded with url: /json-rpc/7.0 (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 407 Proxy Authentication Required',)))
``

**Comment by ahaid** [comment]
Can you share the code that generated this error?

**Comment by arjun960** [comment]
The sfe object initialization is not correct here. Please pass the correct storage array ip, username and password while creating connection.
Hence closing the issue.
