### ISSUE TITLE
Cannot define CHAPSecrets whatsoever

### ISSUE THREAD

**Issue by dirtycajunrice** [solidfire/solidfire-sdk-python#42]
PreCode used:
```py
from solidfire.factory import ElementFactory
from solidfire import common, QoS, CHAPSecret
serverip = '<ip-address>'
username = '<username>'
password = '<password>'
server = ElementFactory.create(serverip, username, password, print_ascii_art=False)
```
This works:
```
newaccount = server.add_account(username='username0')
```
This Does not:
```
newaccount = server.add_account(username='username1', initiator_secret=CHAPSecret('<randomstring>'))
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
TypeError: __init__() takes 1 positional argument but 2 were given
```
Nor does this (being verbose and specifying everything):
```
newaccount = server.add_account(username='username2', initiator_secret=CHAPSecret(secret='<randomstring>'), target_secret=CHAPSecret(secret='<randomstring>'))
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/solidfire/__init__.py", line 90, in add_account
    since=1.0
  File "/usr/local/lib/python3.5/dist-packages/solidfire/common/__init__.py", line 606, in send_request
    encoded = json.dumps(request_dict)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <class 'str'> is not JSON serializable
```
To be completely thorough i also tried adding then modifying:
```
newaccount = server.add_account(username='username3')
server.modify_account(account_id=newaccount.account.account_id, target_secret=CHAPSecret(secret='<randomstring>'))
Traceback (most recent call last):
  File "/usr/lib/python3.5/code.py", line 91, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/solidfire/__init__.py", line 257, in modify_account
    since=1.0
  File "/usr/local/lib/python3.5/dist-packages/solidfire/common/__init__.py", line 606, in send_request
    encoded = json.dumps(request_dict)
  File "/usr/lib/python3.5/json/__init__.py", line 230, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib/python3.5/json/encoder.py", line 198, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib/python3.5/json/encoder.py", line 256, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib/python3.5/json/encoder.py", line 179, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: <class 'str'> is not JSON serializable
```

These tries are a culmination of your documentation [here](https://github.com/solidfire/solidfire-sdk-python/blob/master/examples/manage_accounts.rst#create-an-account) as well as my previous issue requests [here](https://github.com/solidfire/solidfire-sdk-python/issues/31) and [here](https://github.com/solidfire/solidfire-sdk-python/issues/28) The latter still not being done it seems.

**Comment by scaleoutsean** [comment]
Your syntax looks wrong. 

This works fine for me.
```
>>> newaccount = server.add_account(username='sean', initiator_secret='0123456789012')
2020-08-02 20:45:38,004 - solidfire.Element - INFO - {"method": "AddAccount", "id": 3, "params": {"username": "sean", "initiatorSecret": "*****"}}
>>> newaccount = sfe.add_account(username='sean1', initiator_secret='0123456789012', target_secret='0123456789012')
2020-08-02 20:49:14,809 - solidfire.Element - INFO - {"method": "AddAccount", "id": 2, "params": {"username": "sean1", "initiatorSecret": "*****", "targetSecret": "*****"}}
```
* Python 3.6.9
* solidfire-sdk-python 1.6.0.124

**Comment by arjun960** [comment]
@dirtycajunrice As the above response resolves your query, closing the issue.
