### ISSUE TITLE
Install error due to enum34 dependency using Python 3.4+, pip 19.0+, and pyproject.toml

### ISSUE THREAD

**Issue by dgilland** [solidfire/solidfire-sdk-python#48]
Ran into this issue where `solidfire-sdk-python` was a dependency in another project that included a `pyproject.toml` file using Python 3.7 and pip 19:

```
# Issue not present prior to pip 19.
$ pip install pip>=19
$ pip install solidfire-sdk-python

$ pip freeze | grep enum34
enum34==1.1.6

# Initial install, everything ok.
$ pip install -e .

# Subsequent install fails.
$ pip install -e .
Obtaining file:///Users/dgilland/projects/solidfire-sdk-python
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/dgilland/.virtualenvs/solidfire-sdk-python/bin/python3.7 /Users/dgilland/.virtualenvs/solidfire-sdk-python/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/w7/0hhqh2c11n38lvksyz8ddgf00000gp/T/pip-build-env-_wi2ppvy/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -- 'setuptools>=40.0' wheel
       cwd: None
  Complete output (14 lines):
  Traceback (most recent call last):
    File "/local/python/3.7.4/lib/python3.7/runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "/local/python/3.7.4/lib/python3.7/runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "/Users/dgilland/.virtualenvs/solidfire-sdk-python/lib/python3.7/site-packages/pip/__main__.py", line 16, in <module>
      from pip._internal import main as _main  # isort:skip # noqa
    File "/Users/dgilland/.virtualenvs/solidfire-sdk-python/lib/python3.7/site-packages/pip/_internal/__init__.py", line 4, in <module>
      import locale
    File "/Users/dgilland/.virtualenvs/solidfire-sdk-python/lib/python3.7/locale.py", line 16, in <module>
      import re
    File "/Users/dgilland/.virtualenvs/solidfire-sdk-python/lib/python3.7/re.py", line 143, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/dgilland/.virtualenvs/solidfire-sdk-python/bin/python3.7 /Users/dgilland/.virtualenvs/solidfire-sdk-python/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /private/var/folders/w7/0hhqh2c11n38lvksyz8ddgf00000gp/T/pip-build-env-_wi2ppvy/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -- 'setuptools>=40.0' wheel Check the logs for full command output.

# Removing enum34 fixes issue.
$ pip uninstall enum34
$ pip install -e .
```

The error above only happens when a project has a `pyproject.toml` file since pip runs different build routines which uses the standard lib's `enum` module. But since `enum34` is installed, pip ends up using `enum34` instead which leads to the above error. After uninstalling `enum34` and running `pip install -e .` again, there's no error.

Since `enum34` is only required for Python < 3.4, a fix for this would be to modify `setup.py` so that `enum34` is only included for Python < 3.4.

**Comment by scaleoutsean** [comment]
This problem also breaks my setup on Ubuntu 18.04 (Python 3.6).

**Comment by arjun960** [comment]
@dgilland We have addressed and resolve this issue and the fix will be available in the next SDK release.
