### ISSUE TITLE
accounts in list_volumes takes list input

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-sdk-python#51]
https://solidfire-sdk-python.readthedocs.io/en/latest/solidfire.html?highlight=node#solidfire.Element.list_volumes specifies `accounts (int)` but int doesn't work here:

```python
>>> sfe.list_volumes(accounts=7)
2020-02-15 19:14:14,453 - solidfire.Element - INFO - {"method": "ListVolumes", "id": 48, "params": {"accounts": 7}}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sean/.local/lib/python3.6/site-packages/solidfire/__init__.py", line 5484, in list_volumes
    since=8.0
  File "/home/sean/.local/lib/python3.6/site-packages/solidfire/common/__init__.py", line 704, in send_request
    response["error"]["message"])
solidfire.common.ApiServerError: ApiServerError(method_name="ListVolumes", err_json=500 xInvalidParameterType accounts: Invalid type: expected array but found 7
)

```
List does:

```python
>>> sfe.list_volumes(accounts=[7])
2020-02-15 19:10:44,402 - solidfire.Element - INFO - {"method": "ListVolumes", "id": 47, "params": {"accounts": [7]}}
ListVolumesResult(volumes='[]')
```

**Comment by arjun960** [comment]
@scaleoutsean We have addressed and resolved this issue and the fix will be available in the next SDK release.
