### ISSUE TITLE
list_iscsisessions() API fails on versions 1.7.0.152, 12.3.0.203

### ISSUE THREAD

**Issue by kalyanbhonagiri16** [solidfire/solidfire-sdk-python#58]
Hi Team,

I see list_iscsisessions() API returns failure when calling using solidfire API

Environment Details:
Solidfire Element OS version: 11.8

OS version:
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian

sfe.list_iscsisessions()
2021-09-22 15:39:30,117 - solidfire.Element - INFO - {"method": "ListISCSISessions", "id": 1, "params": {}}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/solidfire/__init__.py", line 8364, in list_iscsisessions
    return self.send_request(
  File "/usr/local/lib/python3.9/site-packages/solidfire/common/__init__.py", line 668, in send_request
    return model.extract(result_type, response['result'])
  File "/usr/local/lib/python3.9/site-packages/solidfire/common/model.py", line 75, in extract
    return_value = typ.extract(src, False)
  File "/usr/local/lib/python3.9/site-packages/solidfire/common/model.py", line 348, in extract
    ctor_dict[name] = prop.extract_from(data_val)
  File "/usr/local/lib/python3.9/site-packages/solidfire/common/model.py", line 160, in extract_from
    return [] if data is None else [extract(self._member_type, x) for x
  File "/usr/local/lib/python3.9/site-packages/solidfire/common/model.py", line 160, in <listcomp>
    return [] if data is None else [extract(self._member_type, x) for x
  File "/usr/local/lib/python3.9/site-packages/solidfire/common/model.py", line 75, in extract
    return_value = typ.extract(src, False)
  File "/usr/local/lib/python3.9/site-packages/solidfire/common/model.py", line 348, in extract
    ctor_dict[name] = prop.extract_from(data_val)
  File "/usr/local/lib/python3.9/site-packages/solidfire/common/model.py", line 168, in extract_from
    return None if data is None else extract(self._member_type, data)
  File "/usr/local/lib/python3.9/site-packages/solidfire/common/model.py", line 75, in extract
    return_value = typ.extract(src, False)
  File "/usr/local/lib/python3.9/site-packages/solidfire/common/model.py", line 344, in extract
    data[prop.member_name()])
KeyError: 'initiatorSecret'

**Comment by arjun960** [comment]
@kalyanbhonagiri16 We are unable to reproduce the issue with any of the SDK versions, we have ran the above api on Element 11.8,12.3 and 12.5 versions using SDK versions 1.7, 12.3 and 12.5 on Debian 10.0 and the API is working fine without any issue.

**Comment by kalyanbhonagiri16** [comment]
Apologies, seems to be an env issue. it is NOT reproducible now. Sorry for thr trouble

**Comment by scaleoutsean** [comment]
I see this with SF 12.3, SDK 12.3, Python 3.10 on Ubuntu 22.04 LTS.

```python
>>> Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
>>> import argparse
>>> import asyncio
>>> import time
>>> from solidfire.factory import ElementFactory
>>> import solidfire.common
>>> import logging
>>> import sys 
>>> 
>>> sfe = ElementFactory.create('192.168.1.30', '***', '***')
2024-05-05 18:04:00,947 - solidfire.Element - INFO - {"method": "GetAPI", "id": 0, "params": {}}
2024-05-05 18:04:00,983 - solidfire.Element - INFO - Connected to 192.168.1.30 using API version 12.5
>>> 
>>> cluster_name = 'PROD'
>>> 
>>> 
>>> sfe.list_iscsisessions()
2024-05-05 18:04:12,288 - solidfire.Element - INFO - {"method": "ListISCSISessions", "id": 1, "params": {}}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/__init__.py", line 8364, in list_iscsisessions
    return self.send_request(
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/__init__.py", line 668, in send_request
    return model.extract(result_type, response['result'])
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 75, in extract
    return_value = typ.extract(src, False)
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 348, in extract
    ctor_dict[name] = prop.extract_from(data_val)
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 160, in extract_from
    return [] if data is None else [extract(self._member_type, x) for x
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 160, in <listcomp>
    return [] if data is None else [extract(self._member_type, x) for x
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 75, in extract
    return_value = typ.extract(src, False)
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 348, in extract
    ctor_dict[name] = prop.extract_from(data_val)
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 168, in extract_from
    return None if data is None else extract(self._member_type, data)
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 75, in extract
    return_value = typ.extract(src, False)
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 344, in extract
    data[prop.member_name()])
KeyError: 'initiatorSecret'
```

Also duplicated on Ubuntu 24.04 LTS, connecting with SDK 12.3 to API endpoint version 12.3 (same as above, just with hard-coded `version` param):

```python
>>> sfe = ElementFactory.create('192.168.1.30', '*****', '****', version='12.3')
2024-05-05 18:20:01,927 - solidfire.Element - INFO - {"method": "GetAPI", "id": 0, "params": {}}
2024-05-05 18:20:01,989 - solidfire.Element - INFO - Connected to 192.168.1.30 using API version 12.3
2024-05-05 18:20:01,989 - solidfire.Element - INFO -       
                                      
>>> sfe.list_iscsisessions()
2024-05-05 18:17:26,625 - solidfire.Element - INFO - {"method": "ListISCSISessions", "id": 3, "params": {}}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.12/site-packages/solidfire/__init__.py", line 8364, in list_iscsisessions
    return self.send_request(
           ^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.12/site-packages/solidfire/common/__init__.py", line 668, in send_request
    return model.extract(result_type, response['result'])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.12/site-packages/solidfire/common/model.py", line 75, in extract
    return_value = typ.extract(src, False)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.12/site-packages/solidfire/common/model.py", line 348, in extract
    ctor_dict[name] = prop.extract_from(data_val)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.12/site-packages/solidfire/common/model.py", line 160, in extract_from
    return [] if data is None else [extract(self._member_type, x) for x
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.12/site-packages/solidfire/common/model.py", line 75, in extract
    return_value = typ.extract(src, False)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.12/site-packages/solidfire/common/model.py", line 348, in extract
    ctor_dict[name] = prop.extract_from(data_val)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.12/site-packages/solidfire/common/model.py", line 168, in extract_from
    return None if data is None else extract(self._member_type, data)
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.12/site-packages/solidfire/common/model.py", line 75, in extract
    return_value = typ.extract(src, False)
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/venv/lib/python3.12/site-packages/solidfire/common/model.py", line 344, in extract
    data[prop.member_name()])
    ~~~~^^^^^^^^^^^^^^^^^^^^
KeyError: 'initiatorSecret'
>>> exit()
```

The second OS/Python environment:

```sh
(venv) sean@ubuntu24:/tmp$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=24.04
DISTRIB_CODENAME=noble
DISTRIB_DESCRIPTION="Ubuntu 24.04 LTS"


(venv) sean@ubuntu24:/tmp$ python3 -m pip list
Package              Version
-------------------- ----------
certifi              2024.2.2
charset-normalizer   3.3.2
enum34               1.1.10
future               1.0.0
idna                 3.7
pip                  24.0
requests             2.31.0
setuptools           69.5.1
solidfire-sdk-python 12.3.0.203
urllib3              2.2.1

```

There's no `initiatorSecret` in that response, so where is that key coming from?

The same with `invoke_sfapi`:

```python
>>> sfe.invoke_sfapi('ListISCSISessions')
2024-05-05 18:27:35,503 - solidfire.Element - INFO - {"method": "ListISCSISessions", "id": 3, "params": {}}
{'sessions': [{'accountID': 0, 'accountName': '', 'authentication': {'authMethod': 'None', 'chapAlgorithm': None, 'chapUsername': None, 'direction': None}, 'createTime': '2024-05-05T09:54:19.517775Z', 'driveID': 1, 'driveIDs': [1], 'initiator': {'alias': 'win2025', 'attributes': {}, 'chapCredentialsID': 0, 'initiatorID': 5, 'initiatorName': 'iqn.1991-05.com.microsoft:win-2025', 'requireChap': False, 'virtualNetworkIDs': [], 'volumeAccessGroups': [4]}, 'initiatorIP': '192.168.105.199:49672', 'initiatorName': 'iqn.1991-05.com.microsoft:win-2025', 'initiatorPortName': 'iqn.1991-05.com.microsoft:win-2025,i,0x400001370001', 'initiatorSessionID': 70368764559361, 'msSinceLastIscsiPDU': 35536, 'msSinceLastScsiCommand': 35536, 'nodeID': 1, 'operationalParameters': {'dataDigest': 'None', 'firstBurstLength': 65536, 'headerDigest': 'None', 'immediateData': True, 'initialR2T': True, 'initiatorMaxRecvDataSegmentLength': 65536, 'maxBurstLength': 262144, 'maxOutstandingR2T': 4, 'sessionType': 'Normal', 'targetMaxRecvDataSegmentLength': 262144}, 'serviceID': 4, 'sessionID': 17180947254, 'targetIP': '192.168.105.29:3260', 'targetName': 'iqn.2010-01.com.solidfire:wcwb.sqldb.136', 'targetPortName': 'iqn.2010-01.com.solidfire:wcwb.sqldb.136,t,0x1', 'virtualNetworkID': 0, 'volumeID': 136, 'volumeInstance': 139750223056640}, {'accountID': 0, 'accountName': '', 'authentication': {'authMethod': 'None', 'chapAlgorithm': None, 'chapUsername': None, 'direction': None}, 'createTime': '2024-05-05T09:54:19.517904Z', 'driveID': 1, 'driveIDs': [1], 'initiator': {'alias': 'win2025', 'attributes': {}, 'chapCredentialsID': 0, 'initiatorID': 5, 'initiatorName': 'iqn.1991-05.com.microsoft:win-2025', 'requireChap': False, 'virtualNetworkIDs': [], 'volumeAccessGroups': [4]}, 'initiatorIP': '192.168.105.199:49673', 'initiatorName': 'iqn.1991-05.com.microsoft:win-2025', 'initiatorPortName': 'iqn.1991-05.com.microsoft:win-2025,i,0x400001370001', 'initiatorSessionID': 70368764559361, 'msSinceLastIscsiPDU': 35542, 'msSinceLastScsiCommand': 35542, 'nodeID': 1, 'operationalParameters': {'dataDigest': 'None', 'firstBurstLength': 65536, 'headerDigest': 'None', 'immediateData': True, 'initialR2T': True, 'initiatorMaxRecvDataSegmentLength': 65536, 'maxBurstLength': 262144, 'maxOutstandingR2T': 4, 'sessionType': 'Normal', 'targetMaxRecvDataSegmentLength': 262144}, 'serviceID': 4, 'sessionID': 17180947255, 'targetIP': '192.168.105.29:3260', 'targetName': 'iqn.2010-01.com.solidfire:wcwb.win1.134', 'targetPortName': 'iqn.2010-01.com.solidfire:wcwb.win1.134,t,0x1', 'virtualNetworkID': 0, 'volumeID': 134, 'volumeInstance': 139730489057280}, {'accountID': 0, 'accountName': '', 'authentication': {'authMethod': 'None', 'chapAlgorithm': None, 'chapUsername': None, 'direction': None}, 'createTime': '2024-05-05T09:54:19.518579Z', 'driveID': 1, 'driveIDs': [1], 'initiator': {'alias': 'win2025', 'attributes': {}, 'chapCredentialsID': 0, 'initiatorID': 5, 'initiatorName': 'iqn.1991-05.com.microsoft:win-2025', 'requireChap': False, 'virtualNetworkIDs': [], 'volumeAccessGroups': [4]}, 'initiatorIP': '192.168.105.199:49674', 'initiatorName': 'iqn.1991-05.com.microsoft:win-2025', 'initiatorPortName': 'iqn.1991-05.com.microsoft:win-2025,i,0x400001370001', 'initiatorSessionID': 70368764559361, 'msSinceLastIscsiPDU': 35537, 'msSinceLastScsiCommand': 35537, 'nodeID': 1, 'operationalParameters': {'dataDigest': 'None', 'firstBurstLength': 65536, 'headerDigest': 'None', 'immediateData': True, 'initialR2T': True, 'initiatorMaxRecvDataSegmentLength': 65536, 'maxBurstLength': 262144, 'maxOutstandingR2T': 4, 'sessionType': 'Normal', 'targetMaxRecvDataSegmentLength': 262144}, 'serviceID': 4, 'sessionID': 17180947256, 'targetIP': '192.168.105.29:3260', 'targetName': 'iqn.2010-01.com.solidfire:wcwb.win2.135', 'targetPortName': 'iqn.2010-01.com.solidfire:wcwb.win2.135,t,0x1', 'virtualNetworkID': 0, 'volumeID': 135, 'volumeInstance': 139739708878080}]}

```

And the same JSON passed directly to the API endpoint works, but even here there's something off: all account-related values look invalid.

```json
{
  "id": 1,
  "result": {
    "sessions": [
      {
        "accountID": 0,
        "accountName": "",
        "authentication": {
          "authMethod": "None",
          "chapAlgorithm": null,
          "chapUsername": null,
          "direction": null
        },
        "createTime": "2024-05-05T09:54:19.517775Z",
        "driveID": 1,
        "driveIDs": [
          1
        ]
...
```

I get the same invalid response in account details with Postman.

Since `ListISCSISessions` account details are wrong in API responses, both SolidFire SDK methods (`list_iscsisessions` and `invoke_sf_api`) are unusable.
