### ISSUE TITLE
list_volume_qos_histograms doesn't seem to work

### ISSUE THREAD

**Issue by scaleoutsean** [solidfire/solidfire-sdk-python#59]
- Python 3.10.12
- solidfire-sdk-python 12.3.0.203

According to the docs, volume_ids are optional.

list_volume_stats and list_volume_qos_histograms is supposed to work the same way, but it doesn't.

```sh
>>> sfe.list_volume_stats()
2023-11-19 00:06:42,763 - solidfire.Element - INFO - {"method": "ListVolumeStats", "id": 19, "params": {}}
ListVolumeStatsResult(volume_stats=....
<snip>

>>> sfe.list_volume_qos_histograms()
2023-11-19 00:06:47,947 - solidfire.Element - INFO - {"method": "ListVolumeQoSHistograms", "id": 20, "params": {}}
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/__init__.py", line 3126, in list_volume_qos_histograms
    return self.send_request(
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/__init__.py", line 668, in send_request
    return model.extract(result_type, response['result'])
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 75, in extract
    return_value = typ.extract(src, False)
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 348, in extract
    ctor_dict[name] = prop.extract_from(data_val)
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 160, in extract_from
    return [] if data is None else [extract(self._member_type, x) for x
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 160, in <listcomp>
    return [] if data is None else [extract(self._member_type, x) for x
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 75, in extract
    return_value = typ.extract(src, False)
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 348, in extract
    ctor_dict[name] = prop.extract_from(data_val)
  File "/home/sean/.local/lib/python3.10/site-packages/solidfire/common/model.py", line 160, in extract_from
    return [] if data is None else [extract(self._member_type, x) for x
TypeError: 'int' object is not iterable
```

It also doesn't work with an array.

![image](https://github.com/solidfire/solidfire-sdk-python/assets/16622642/c059d403-500c-447b-9943-27d6e3074d23)

**Comment by scaleoutsean** [comment]
Forgot to mention in the case somebody comes across this before it's fixed: the old "invoke" workaround still works fine.

```python
sfe.invoke_sfapi("ListVolumeQoSHistograms", parameters={"volume_ids": [1]})
```

**Comment by scaleoutsean** [comment]
Doh... Should be `VolumeIDs`, not `volumeIDs`...

```json
{
  "method": "ListVolumeQoSHistograms",
    "params": {
      "VolumeIDs": [134]
    },
    "id": 1
}
```
